### ISSUE TITLE
pyup_dirs crashes with an ImportError

### ISSUE THREAD

**Issue by brunobord** [domdfcoding/pyupgrade-directories#13]
## Description

Running pyup_dirs crashes with the latest pyupgrade (2.9.0) version.
Using a fresh install of pyupgrade and pyupgrade-directories, the tool doesn't even start and crashes because of an `ImportError`

## Steps to Reproduce

```console
$ virtualenv python=python3.6 /tmp/venv
$ source /tmp/venv/bin/activate
$ pip install pyupgrade-directories
[snip]
$ pyup_dirs
Traceback (most recent call last):
  File "/tmp/venv/bin/pyup_dirs", line 5, in <module>
    from pyupgrade_directories.__main__ import main
  File "/tmp/venv/lib/python3.6/site-packages/pyupgrade_directories/__main__.py", line 21, in <module>
    from pyupgrade import _fix_file  # type: ignore
ImportError: cannot import name '_fix_file'
```

## Expected result:

The application checks my source files.

## Reproduces how often:

All the time.

## Version

  * Operating System: Linux (Ubuntu)
  * Python: Tested with Python 3.6, 3.7. Doesn't looks like it's related to the python version
  * pyupgrade-directories: 0.0.3
  * Important note: I've tested with downgraded versions of `pyupgrade` ; it looks like the latest "working" version is the 2.7.4, so it means that the ImportError happens with versions 2.8.0 & 2.9.0 of `pyupgrade`

**Comment by aleksandr-kotlyar** [comment]
Seems pyupgrade-directories needs to be adopted to the latest pyupgrade library and make a new release 0.0.4 with supporting <2.8 and 0.0.5 adopted to the latest pyupgrade version.

**Comment by aleksandr-kotlyar** [comment]
I see 0.1.0 version is almost ready with fix and import checks. @domdfcoding can you please make a release and upload to pypi?

**Comment by domdfcoding** [comment]
Hi @brunobord and @aleksandr-kotlyar .

Terribly sorry, I completely forgot about this. I have made a new release ([v0.1.1](https://pypi.org/project/pyupgrade-directories/0.1.1/)) which sets the maximum version of pyupgrade to 2.7.4 and so will run correctly. I am working on supporting newer pyupgrade versions right now.

**Comment by aleksandr-kotlyar** [comment]
> I have made a new release (v0.1.1) which sets the maximum version of pyupgrade to 2.7.4 and so will run correctly.

@domdfcoding thank you very much! I have tested reinstallation of pyupgrade-directories on the top lvl pyupgrade, and it works fine - reinstalling newer pyupgrade to the 2.7.4.
![image](https://user-images.githubusercontent.com/17043964/109431954-0a91d580-7a1a-11eb-86ae-c11b81e15c2a.png)

> I am working on supporting newer pyupgrade versions right now.

Cool! If will need you any help just dive us into the details through issues.

**Comment by brunobord** [comment]
looks like it's solved, yes! Thank you very much!
